insert into public.farms(slug,name,total_chickens,total_property_area,profile) values('green-peas','Green Peas',90,null,'{"location":"Jeita, Lebanon","elevation_approx_m":400}'::jsonb);
insert into public.farm_members(farm_id,email,role) select id,'chrisonline108@gmail.com','owner' from public.farms where slug='green-peas';
insert into public.areas(farm_id,name,kind) select id,'Ruin','facility' from public.farms where slug='green-peas';
insert into public.areas(farm_id,name,kind) select id,'Cellar','facility' from public.farms where slug='green-peas';
insert into public.areas(farm_id,name,kind) select id,'Chicken Coop A','facility' from public.farms where slug='green-peas';
insert into public.areas(farm_id,name,kind) select id,'Chicken Coop B','facility' from public.farms where slug='green-peas';
insert into public.areas(farm_id,name,kind) select id,'Toolshed','facility' from public.farms where slug='green-peas';
insert into public.areas(farm_id,name,kind) select id,'Irrigation Station','facility' from public.farms where slug='green-peas';
insert into public.areas(farm_id,name,kind) select id,'Marketplace / Breakfast Section','facility' from public.farms where slug='green-peas';
insert into public.areas(farm_id,name,kind) select id,'Zone 5','facility' from public.farms where slug='green-peas';
insert into public.areas(farm_id,name,kind) select id,'Compost System','facility' from public.farms where slug='green-peas';
insert into public.areas(farm_id,name,kind) select id,'Sheep and Goat House','facility' from public.farms where slug='green-peas';
insert into public.areas(farm_id,name,kind) select id,'Ferre House','facility' from public.farms where slug='green-peas';
insert into public.areas(farm_id,name,kind) select id,'Ducks House','facility' from public.farms where slug='green-peas';
insert into public.areas(farm_id,name,kind) select id,'Vehicle Shed','facility' from public.farms where slug='green-peas';
insert into public.areas(farm_id,name,kind) select id,'Nursery','facility' from public.farms where slug='green-peas';
insert into public.areas(farm_id,name,kind) select id,'Storage','facility' from public.farms where slug='green-peas';
insert into public.areas(farm_id,name,kind,classification) select id,'Z1','production','Greenhouse' from public.farms where slug='green-peas';
insert into public.beds(farm_id,area_id,code,length_m,width_m,purpose) select farm_id,id,'Z1-B1',23,0.8,'Production' from public.areas where name='Z1' and farm_id=(select id from public.farms where slug='green-peas');
insert into public.beds(farm_id,area_id,code,length_m,width_m,purpose) select farm_id,id,'Z1-B2',23,0.8,'Production' from public.areas where name='Z1' and farm_id=(select id from public.farms where slug='green-peas');
insert into public.beds(farm_id,area_id,code,length_m,width_m,purpose) select farm_id,id,'Z1-B3',23,0.8,'Production' from public.areas where name='Z1' and farm_id=(select id from public.farms where slug='green-peas');
insert into public.beds(farm_id,area_id,code,length_m,width_m,purpose) select farm_id,id,'Z1-B4',23,0.8,'Production' from public.areas where name='Z1' and farm_id=(select id from public.farms where slug='green-peas');
insert into public.beds(farm_id,area_id,code,length_m,width_m,purpose) select farm_id,id,'Z1-B5',23,0.8,'Production' from public.areas where name='Z1' and farm_id=(select id from public.farms where slug='green-peas');
insert into public.areas(farm_id,name,kind,classification) select id,'Z2','production','Greenhouse' from public.farms where slug='green-peas';
insert into public.beds(farm_id,area_id,code,length_m,width_m,purpose) select farm_id,id,'Z2-B1',28,0.8,'Production' from public.areas where name='Z2' and farm_id=(select id from public.farms where slug='green-peas');
insert into public.beds(farm_id,area_id,code,length_m,width_m,purpose) select farm_id,id,'Z2-B2',28,0.8,'Production' from public.areas where name='Z2' and farm_id=(select id from public.farms where slug='green-peas');
insert into public.beds(farm_id,area_id,code,length_m,width_m,purpose) select farm_id,id,'Z2-B3',28,0.8,'Production' from public.areas where name='Z2' and farm_id=(select id from public.farms where slug='green-peas');
insert into public.beds(farm_id,area_id,code,length_m,width_m,purpose) select farm_id,id,'Z2-B4',28,0.8,'Production' from public.areas where name='Z2' and farm_id=(select id from public.farms where slug='green-peas');
insert into public.beds(farm_id,area_id,code,length_m,width_m,purpose) select farm_id,id,'Z2-B5',28,0.8,'Production' from public.areas where name='Z2' and farm_id=(select id from public.farms where slug='green-peas');
insert into public.areas(farm_id,name,kind,classification) select id,'Z7','production','Polytunnel' from public.farms where slug='green-peas';
insert into public.beds(farm_id,area_id,code,length_m,width_m,purpose) select farm_id,id,'Z7-B1',20,0.8,'Production' from public.areas where name='Z7' and farm_id=(select id from public.farms where slug='green-peas');
insert into public.beds(farm_id,area_id,code,length_m,width_m,purpose) select farm_id,id,'Z7-B2',20,0.8,'Production' from public.areas where name='Z7' and farm_id=(select id from public.farms where slug='green-peas');
insert into public.beds(farm_id,area_id,code,length_m,width_m,purpose) select farm_id,id,'Z7-B3',10,0.8,'Production' from public.areas where name='Z7' and farm_id=(select id from public.farms where slug='green-peas');
insert into public.areas(farm_id,name,kind,classification) select id,'Z8','production','Polytunnel' from public.farms where slug='green-peas';
insert into public.beds(farm_id,area_id,code,length_m,width_m,purpose) select farm_id,id,'Z8-B1',16,0.8,'Production' from public.areas where name='Z8' and farm_id=(select id from public.farms where slug='green-peas');
insert into public.beds(farm_id,area_id,code,length_m,width_m,purpose) select farm_id,id,'Z8-B2',16,0.8,'Production' from public.areas where name='Z8' and farm_id=(select id from public.farms where slug='green-peas');
insert into public.areas(farm_id,name,kind,classification) select id,'Z9','production','Polytunnel' from public.farms where slug='green-peas';
insert into public.beds(farm_id,area_id,code,length_m,width_m,purpose) select farm_id,id,'Z9-B1',25,0.8,'Production' from public.areas where name='Z9' and farm_id=(select id from public.farms where slug='green-peas');
insert into public.beds(farm_id,area_id,code,length_m,width_m,purpose) select farm_id,id,'Z9-B2',25,0.8,'Production' from public.areas where name='Z9' and farm_id=(select id from public.farms where slug='green-peas');
insert into public.areas(farm_id,name,kind,classification) select id,'Z10','production','Polytunnel' from public.farms where slug='green-peas';
insert into public.beds(farm_id,area_id,code,length_m,width_m,purpose) select farm_id,id,'Z10-B1',35,0.8,'Production' from public.areas where name='Z10' and farm_id=(select id from public.farms where slug='green-peas');
insert into public.beds(farm_id,area_id,code,length_m,width_m,purpose) select farm_id,id,'Z10-B2',35,0.8,'Production' from public.areas where name='Z10' and farm_id=(select id from public.farms where slug='green-peas');
insert into public.areas(farm_id,name,kind,classification) select id,'Z13','production','Open Field' from public.farms where slug='green-peas';
insert into public.beds(farm_id,area_id,code,length_m,width_m,purpose) select farm_id,id,'Z13-B1',30,0.8,'Production' from public.areas where name='Z13' and farm_id=(select id from public.farms where slug='green-peas');
insert into public.beds(farm_id,area_id,code,length_m,width_m,purpose) select farm_id,id,'Z13-B2',30,0.8,'Production' from public.areas where name='Z13' and farm_id=(select id from public.farms where slug='green-peas');
insert into public.beds(farm_id,area_id,code,length_m,width_m,purpose) select farm_id,id,'Z13-B3',30,0.8,'Production' from public.areas where name='Z13' and farm_id=(select id from public.farms where slug='green-peas');
insert into public.areas(farm_id,name,kind,classification) select id,'Z14','production','Open Field' from public.farms where slug='green-peas';
insert into public.beds(farm_id,area_id,code,length_m,width_m,purpose) select farm_id,id,'Z14-B1',15,0.8,'Production' from public.areas where name='Z14' and farm_id=(select id from public.farms where slug='green-peas');
insert into public.beds(farm_id,area_id,code,length_m,width_m,purpose) select farm_id,id,'Z14-B2',15,0.8,'Production' from public.areas where name='Z14' and farm_id=(select id from public.farms where slug='green-peas');
insert into public.beds(farm_id,area_id,code,length_m,width_m,purpose) select farm_id,id,'Z14-B3',15,0.8,'Production' from public.areas where name='Z14' and farm_id=(select id from public.farms where slug='green-peas');
insert into public.areas(farm_id,name,kind,classification) select id,'Y1','production','Polytunnel' from public.farms where slug='green-peas';
insert into public.beds(farm_id,area_id,code,length_m,width_m,purpose) select farm_id,id,'Y1-B1',15,0.8,'Production' from public.areas where name='Y1' and farm_id=(select id from public.farms where slug='green-peas');
insert into public.beds(farm_id,area_id,code,length_m,width_m,purpose) select farm_id,id,'Y1-B2',15,0.8,'Production' from public.areas where name='Y1' and farm_id=(select id from public.farms where slug='green-peas');
insert into public.beds(farm_id,area_id,code,length_m,width_m,purpose) select farm_id,id,'Y1-B3',15,0.8,'Production' from public.areas where name='Y1' and farm_id=(select id from public.farms where slug='green-peas');
insert into public.areas(farm_id,name,kind,classification) select id,'Y2','production','Open Field' from public.farms where slug='green-peas';
insert into public.beds(farm_id,area_id,code,length_m,width_m,purpose) select farm_id,id,'Y2-B1',15,0.8,'Production' from public.areas where name='Y2' and farm_id=(select id from public.farms where slug='green-peas');
insert into public.beds(farm_id,area_id,code,length_m,width_m,purpose) select farm_id,id,'Y2-B2',15,0.8,'Production' from public.areas where name='Y2' and farm_id=(select id from public.farms where slug='green-peas');
insert into public.areas(farm_id,name,kind,classification) select id,'S1','production','Polytunnel' from public.farms where slug='green-peas';
insert into public.beds(farm_id,area_id,code,length_m,width_m,purpose) select farm_id,id,'S1',6,1.5,'Production' from public.areas where name='S1' and farm_id=(select id from public.farms where slug='green-peas');
insert into public.areas(farm_id,name,kind,classification) select id,'S2','production','Polytunnel' from public.farms where slug='green-peas';
insert into public.beds(farm_id,area_id,code,length_m,width_m,purpose) select farm_id,id,'S2',6,1.5,'Production' from public.areas where name='S2' and farm_id=(select id from public.farms where slug='green-peas');
insert into public.areas(farm_id,name,kind,classification) select id,'S3','production','Polytunnel' from public.farms where slug='green-peas';
insert into public.beds(farm_id,area_id,code,length_m,width_m,purpose) select farm_id,id,'S3',6,1.5,'Production' from public.areas where name='S3' and farm_id=(select id from public.farms where slug='green-peas');
insert into public.areas(farm_id,name,kind,classification) select id,'S4','production','Polytunnel' from public.farms where slug='green-peas';
insert into public.beds(farm_id,area_id,code,length_m,width_m,purpose) select farm_id,id,'S4',6,1.5,'Production' from public.areas where name='S4' and farm_id=(select id from public.farms where slug='green-peas');
insert into public.areas(farm_id,name,kind,classification) select id,'S5','production','Polytunnel' from public.farms where slug='green-peas';
insert into public.beds(farm_id,area_id,code,length_m,width_m,purpose) select farm_id,id,'S5',6,1.5,'Production' from public.areas where name='S5' and farm_id=(select id from public.farms where slug='green-peas');
insert into public.areas(farm_id,name,kind,classification) select id,'S6','production','Open Field' from public.farms where slug='green-peas';
insert into public.beds(farm_id,area_id,code,length_m,width_m,purpose) select farm_id,id,'S6',6,1.5,'Production' from public.areas where name='S6' and farm_id=(select id from public.farms where slug='green-peas');
insert into public.areas(farm_id,name,kind,classification) select id,'S7','production','Polytunnel' from public.farms where slug='green-peas';
insert into public.beds(farm_id,area_id,code,length_m,width_m,purpose) select farm_id,id,'S7',6,1.5,'Production' from public.areas where name='S7' and farm_id=(select id from public.farms where slug='green-peas');
insert into public.areas(farm_id,name,kind,classification) select id,'S8','production','Reserve / Habitat' from public.farms where slug='green-peas';
insert into public.beds(farm_id,area_id,code,length_m,width_m,purpose) select farm_id,id,'S8',6,1.5,'Reserve / Habitat' from public.areas where name='S8' and farm_id=(select id from public.farms where slug='green-peas');
insert into public.areas(farm_id,name,kind,classification) select id,'S9','production','Reserve / Habitat' from public.farms where slug='green-peas';
insert into public.beds(farm_id,area_id,code,length_m,width_m,purpose) select farm_id,id,'S9',6,1.5,'Reserve / Habitat' from public.areas where name='S9' and farm_id=(select id from public.farms where slug='green-peas');
insert into public.coops(farm_id,area_id,name) select farm_id,id,name from public.areas where name='Chicken Coop A';
insert into public.coops(farm_id,area_id,name) select farm_id,id,name from public.areas where name='Chicken Coop B';
insert into public.workers(farm_id,name,role,phone) select id,'Haidar','Farm operations',null from public.farms where slug='green-peas';
insert into public.workers(farm_id,name,role,phone) select id,'Soufe','Farm operations',null from public.farms where slug='green-peas';
insert into public.workers(farm_id,name,role,phone) select id,'Fady','Farm operations',null from public.farms where slug='green-peas';
insert into public.workers(farm_id,name,role,phone) select id,'Koussai','Farm operations',null from public.farms where slug='green-peas';
insert into public.workers(farm_id,name,role,phone) select id,'Omran','Farm operations',null from public.farms where slug='green-peas';
insert into public.workers(farm_id,name,role,phone) select id,'Yamen','Farm operations',null from public.farms where slug='green-peas';
insert into public.workers(farm_id,name,role,phone) select id,'Amjat','Farm operations',null from public.farms where slug='green-peas';
insert into public.workers(farm_id,name,role,phone) select id,'Hsein','Farm operations',null from public.farms where slug='green-peas';
insert into public.workers(farm_id,name,role,phone) select id,'Jassem','Farm operations',null from public.farms where slug='green-peas';
insert into public.workers(farm_id,name,role,phone) select id,'Chris','Farm operations',null from public.farms where slug='green-peas';
insert into public.inventory(farm_id,item,category,qty,min) select id,'Chicken feed','Feed',null,null from public.farms where slug='green-peas';
insert into public.inventory(farm_id,item,category,qty,min) select id,'Seeds / seed lots','Seeds',null,null from public.farms where slug='green-peas';
insert into public.inventory(farm_id,item,category,qty,min) select id,'Seedlings / transplants','Seedlings',null,null from public.farms where slug='green-peas';
insert into public.inventory(farm_id,item,category,qty,min) select id,'Chicken bedding','Chicken bedding',null,null from public.farms where slug='green-peas';
insert into public.inventory(farm_id,item,category,qty,min) select id,'Mulch','Other',null,null from public.farms where slug='green-peas';
insert into public.inventory(farm_id,item,category,qty,min) select id,'Nursery trays / media','Nursery',null,null from public.farms where slug='green-peas';
insert into public.inventory(farm_id,item,category,qty,min) select id,'Drip line / emitters / connectors / valves','Irrigation',null,null from public.farms where slug='green-peas';
insert into public.inventory(farm_id,item,category,qty,min) select id,'Trellis material','Other',null,null from public.farms where slug='green-peas';
insert into public.inventory(farm_id,item,category,qty,min) select id,'Packaging / egg packaging','Packaging',null,null from public.farms where slug='green-peas';
insert into public.inventory(farm_id,item,category,qty,min) select id,'Harvest crates','Other',null,null from public.farms where slug='green-peas';
insert into public.inventory(farm_id,item,category,qty,min) select id,'Cleaning / sanitation materials','Cleaning',null,null from public.farms where slug='green-peas';
insert into public.inventory(farm_id,item,category,qty,min) select id,'PPE / hand tools / replacement parts','Tools / PPE',null,null from public.farms where slug='green-peas';
insert into public.inventory(farm_id,item,category,qty,min) select id,'Azaxol','Treatment',null,null from public.farms where slug='green-peas';
insert into public.inventory(farm_id,item,category,qty,min) select id,'Insectazol','Treatment',null,null from public.farms where slug='green-peas';
insert into public.inventory(farm_id,item,category,qty,min) select id,'Silazelle','Treatment',null,null from public.farms where slug='green-peas';
insert into public.inventory(farm_id,item,category,qty,min) select id,'Spinozad','Treatment',null,null from public.farms where slug='green-peas';
insert into public.inventory(farm_id,item,category,qty,min) select id,'Bt','Treatment',null,null from public.farms where slug='green-peas';
insert into public.inventory(farm_id,item,category,qty,min) select id,'Soap','Treatment',null,null from public.farms where slug='green-peas';
insert into public.inventory(farm_id,item,category,qty,min) select id,'Pepper','Treatment',null,null from public.farms where slug='green-peas';
insert into public.inventory(farm_id,item,category,qty,min) select id,'Neem oil','Treatment',null,null from public.farms where slug='green-peas';
insert into public.inventory(farm_id,item,category,qty,min) select id,'Vermi compost','Fertilizer / amendment',null,null from public.farms where slug='green-peas';
insert into public.inventory(farm_id,item,category,qty,min) select id,'Compost','Fertilizer / amendment',null,null from public.farms where slug='green-peas';
insert into public.inventory(farm_id,item,category,qty,min) select id,'Humic acid','Fertilizer / amendment',null,null from public.farms where slug='green-peas';
insert into public.inventory(farm_id,item,category,qty,min) select id,'Sugar','Fertilizer / amendment',null,null from public.farms where slug='green-peas';
insert into public.inventory(farm_id,item,category,qty,min) select id,'Seaweed','Fertilizer / amendment',null,null from public.farms where slug='green-peas';
insert into public.inventory(farm_id,item,category,qty,min) select id,'Beneficial bacteria','Fertilizer / amendment',null,null from public.farms where slug='green-peas';
insert into public.inventory(farm_id,item,category,qty,min) select id,'Weeds','Fertilizer / amendment',null,null from public.farms where slug='green-peas';
insert into public.inventory(farm_id,item,category,qty,min) select id,'Sheepwhool pellets','Fertilizer / amendment',null,null from public.farms where slug='green-peas';
insert into public.inventory(farm_id,item,category,qty,min) select id,'Wood Ash','Fertilizer / amendment',null,null from public.farms where slug='green-peas';
insert into public.inventory(farm_id,item,category,qty,min) select id,'Coffee eshre','Fertilizer / amendment',null,null from public.farms where slug='green-peas';
insert into public.tasks(farm_id,title,event_type,recurrence,weekday,routine_key,area_id) select id,'Harvest readiness','Harvest','Daily',null,'Daily::Harvest readiness',null from public.farms f where slug='green-peas';
insert into public.tasks(farm_id,title,event_type,recurrence,weekday,routine_key,area_id) select id,'Weather','Other','Daily',null,'Daily::Weather',null from public.farms f where slug='green-peas';
insert into public.tasks(farm_id,title,event_type,recurrence,weekday,routine_key,area_id) select id,'Soil moisture','Irrigation','Daily',null,'Daily::Soil moisture',null from public.farms f where slug='green-peas';
insert into public.tasks(farm_id,title,event_type,recurrence,weekday,routine_key,area_id) select id,'Irrigation','Irrigation','Daily',null,'Daily::Irrigation',null from public.farms f where slug='green-peas';
insert into public.tasks(farm_id,title,event_type,recurrence,weekday,routine_key,area_id) select id,'Nursery / germination','Nursery','Daily',null,'Daily::Nursery / germination',null from public.farms f where slug='green-peas';
insert into public.tasks(farm_id,title,event_type,recurrence,weekday,routine_key,area_id) select id,'Pest/disease check','Scouting','Daily',null,'Daily::Pest/disease check',null from public.farms f where slug='green-peas';
insert into public.tasks(farm_id,title,event_type,recurrence,weekday,routine_key,area_id) select id,'Food-safety check','Farm task','Daily',null,'Daily::Food-safety check',null from public.farms f where slug='green-peas';
insert into public.tasks(farm_id,title,event_type,recurrence,weekday,routine_key,area_id) select id,'Field work','Farm task','Daily',null,'Daily::Field work',null from public.farms f where slug='green-peas';
insert into public.tasks(farm_id,title,event_type,recurrence,weekday,routine_key,area_id) select id,'Coop work','Coop','Daily',null,'Daily::Coop work',null from public.farms f where slug='green-peas';
insert into public.tasks(farm_id,title,event_type,recurrence,weekday,routine_key,area_id) select id,'Review demand vs next 14 days of production','Farm task','Weekly',0,'Weekly:0:Review demand vs next 14 days of production',null from public.farms f where slug='green-peas';
insert into public.tasks(farm_id,title,event_type,recurrence,weekday,routine_key,area_id) select id,'Crop scouting','Scouting','Weekly',1,'Weekly:1:Crop scouting',null from public.farms f where slug='green-peas';
insert into public.tasks(farm_id,title,event_type,recurrence,weekday,routine_key,area_id) select id,'14-day outlook','Farm task','Weekly',1,'Weekly:1:14-day outlook',null from public.farms f where slug='green-peas';
insert into public.tasks(farm_id,title,event_type,recurrence,weekday,routine_key,area_id) select id,'Crop review','Farm task','Weekly',2,'Weekly:2:Crop review',null from public.farms f where slug='green-peas';
insert into public.tasks(farm_id,title,event_type,recurrence,weekday,routine_key,area_id) select id,'Fertility review','Fertility','Weekly',2,'Weekly:2:Fertility review',null from public.farms f where slug='green-peas';
insert into public.tasks(farm_id,title,event_type,recurrence,weekday,routine_key,area_id) select id,'Weeding','Farm task','Weekly',3,'Weekly:3:Weeding',null from public.farms f where slug='green-peas';
insert into public.tasks(farm_id,title,event_type,recurrence,weekday,routine_key,area_id) select id,'Drainage','Maintenance','Weekly',3,'Weekly:3:Drainage',null from public.farms f where slug='green-peas';
insert into public.tasks(farm_id,title,event_type,recurrence,weekday,routine_key,area_id) select id,'Traps/screens','Scouting','Weekly',3,'Weekly:3:Traps/screens',null from public.farms f where slug='green-peas';
insert into public.tasks(farm_id,title,event_type,recurrence,weekday,routine_key,area_id) select id,'Disease-risk review','Scouting','Weekly',4,'Weekly:4:Disease-risk review',null from public.farms f where slug='green-peas';
insert into public.tasks(farm_id,title,event_type,recurrence,weekday,routine_key,area_id) select id,'Detailed pest scouting','Scouting','Weekly',5,'Weekly:5:Detailed pest scouting',null from public.farms f where slug='green-peas';
insert into public.tasks(farm_id,title,event_type,recurrence,weekday,routine_key,area_id) select id,'Trellising','Farm task','Weekly',5,'Weekly:5:Trellising',null from public.farms f where slug='green-peas';
insert into public.tasks(farm_id,title,event_type,recurrence,weekday,routine_key,area_id) select id,'Maintenance','Maintenance','Weekly',5,'Weekly:5:Maintenance',null from public.farms f where slug='green-peas';
insert into public.tasks(farm_id,title,event_type,recurrence,weekday,routine_key,area_id) select id,'Harvest','Harvest','Weekly',6,'Weekly:6:Harvest',null from public.farms f where slug='green-peas';
insert into public.tasks(farm_id,title,event_type,recurrence,weekday,routine_key,area_id) select id,'Packing','Farm task','Weekly',6,'Weekly:6:Packing',null from public.farms f where slug='green-peas';
insert into public.tasks(farm_id,title,event_type,recurrence,weekday,routine_key,area_id) select id,'Sales records','Farm task','Weekly',6,'Weekly:6:Sales records',null from public.farms f where slug='green-peas';
insert into public.tasks(farm_id,title,event_type,recurrence,weekday,routine_key,area_id) select id,'Marketplace / Breakfast Section use','Farm task','Weekly',6,'Weekly:6:Marketplace / Breakfast Section use',(select id from public.areas where name='Marketplace / Breakfast Section' and farm_id=f.id) from public.farms f where slug='green-peas';
insert into public.tasks(farm_id,title,event_type,recurrence,weekday,routine_key,area_id) select id,'Waste recording','Farm task','Weekly',6,'Weekly:6:Waste recording',null from public.farms f where slug='green-peas';
insert into public.tasks(farm_id,title,event_type,recurrence,weekday,routine_key,area_id) select id,'Inventory count','Farm task','Monthly',null,'Monthly::Inventory count',null from public.farms f where slug='green-peas';
insert into public.tasks(farm_id,title,event_type,recurrence,weekday,routine_key,area_id) select id,'Crop-performance review','Farm task','Monthly',null,'Monthly::Crop-performance review',null from public.farms f where slug='green-peas';
insert into public.tasks(farm_id,title,event_type,recurrence,weekday,routine_key,area_id) select id,'Egg/flock review','Coop','Monthly',null,'Monthly::Egg/flock review',null from public.farms f where slug='green-peas';
insert into public.tasks(farm_id,title,event_type,recurrence,weekday,routine_key,area_id) select id,'Irrigation maintenance','Maintenance','Monthly',null,'Monthly::Irrigation maintenance',null from public.farms f where slug='green-peas';
insert into public.tasks(farm_id,title,event_type,recurrence,weekday,routine_key,area_id) select id,'Tools/equipment check','Maintenance','Monthly',null,'Monthly::Tools/equipment check',null from public.farms f where slug='green-peas';
insert into public.tasks(farm_id,title,event_type,recurrence,weekday,routine_key,area_id) select id,'Input-cost review','Farm task','Monthly',null,'Monthly::Input-cost review',null from public.farms f where slug='green-peas';
insert into public.tasks(farm_id,title,event_type,recurrence,weekday,routine_key,area_id) select id,'Production-vs-sales review','Farm task','Monthly',null,'Monthly::Production-vs-sales review',null from public.farms f where slug='green-peas';
