const fs = require('fs');
let html = fs.readFileSync('C:/Users/Roger/Downloads/Green peas Farm Os.html', 'utf8');
const facilities = ['Ruin','Cellar','Chicken Coop A','Chicken Coop B','Toolshed','Irrigation Station','Marketplace / Breakfast Section','Zone 5','Compost System','Sheep and Goat House','Ferre House','Ducks House','Vehicle Shed','Nursery','Storage'];
const production = [['Z1','Greenhouse'],['Z2','Greenhouse'],...['Z7','Z8','Z9','Z10'].map(x=>[x,'Polytunnel']),['Z13','Open Field'],['Z14','Open Field'],['Y1','Polytunnel'],['Y2','Open Field'],...['S1','S2','S3','S4','S5'].map(x=>[x,'Polytunnel']),['S6','Open Field'],['S7','Polytunnel'],['S8','Reserve / Habitat'],['S9','Reserve / Habitat']];
function section(id, content) { html = html.replace(new RegExp('<section id="'+id+'"[\\s\\S]*?</section>'), '<section id="'+id+'" class="view">'+content+'</section>'); }
html = html.replace('<title>Farm OS</title>', '<title>Green Peas Farm OS</title>');
html = html.replace('<a href="#farm">🚜 Farm</a>', '<a href="#farm">🚜 Farm</a><a href="#areas">🏡 Farm Areas</a>');
html = html.replace('<a href="#home"><b>🏠</b>Home</a>', '<a href="#areas"><b>🏡</b>Areas</a>');
html = html.replace(/<div class="card">\s*<div class="section-title"><div><h3>General farm facilities & areas<\/h3>[\s\S]*?(?=\s*<div class="card">\s*<div class="section-title"><h3>Irrigation)/, '<div class="card"><h3>Farm Areas / Facilities</h3><p>15 confirmed areas. Total property area: <b>TBC</b>.</p><a class="btn primary" href="#areas">Open Farm Areas</a></div>');
html = html.replace(/<div class="clean"><div class="meta">Operating baseline[\s\S]*?<\/div><\/div>/, '<div class="clean"><div class="meta">Eggs collected</div><b>Not recorded yet</b></div>');
html = html.replace(/<div class="clean"><div class="meta">Operational target[\s\S]*?<\/div><\/div>/, '<div class="clean"><div class="meta">Egg target</div><b>TBC</b></div>');
html = html.replace('separately where possible', 'separately for every record');
html = html.replace('Coop A + Coop B · bird split TBC', 'Coop A + Coop B · <span class="birdSplit">bird split TBC</span>');
html = html.replace('Total flock remains 90; birds per coop are TBC.', 'Total flock remains 90. <span class="birdSplit">Birds per coop: TBC.</span>');
html = html.replace(/<div class="row"><span>🌱<\/span><div><b>S2<\/b>[\s\S]*?<\/div><\/div><\/div>/, '<div class="row"><div><b>Actual crop locations and planting dates</b><div class="meta">Not recorded yet</div></div></div>');
html = html.replace(/S2 is the only bed currently confirmed in the source information as active with <b>eggplant \+ rocca<\/b>\./, 'Actual crop locations and planting dates: Not recorded yet.');
html = html.replace('<tr><td><b>S</b></td><td>S7–S9</td><td>Polytunnel</td><td>6 × 1.5 m each</td><td>27.0 m²</td></tr>', '<tr><td><b>S</b></td><td>S7</td><td>Polytunnel</td><td>6 × 1.5 m</td><td>9.0 m²</td></tr><tr><td><b>S</b></td><td>S8, S9</td><td>Reserve / Habitat</td><td>6 × 1.5 m each</td><td>18.0 m²</td></tr>');
const areas = `<section id="areas" class="view"><div class="section-title"><div><h2>Farm Areas / Facilities</h2><p class="sub">Confirmed Green Peas area register</p></div><a class="btn" href="#home">Dashboard</a></div><div class="card"><b>Total property area: TBC</b><p>Facility dimensions, capacity, coordinates, layout and other details are TBC unless recorded. The farm has 90 chickens in total; the count in each coop is TBC.</p></div><div class="grid2">${facilities.map(name=>`<div class="card facility"><h3>${name}</h3><div class="meta">Dimensions · capacity · coordinates · layout: TBC</div><p>Details: Not recorded yet</p>${name.startsWith('Chicken Coop')?`<a class="btn" href="#coop" data-open-coop="${name}">Open coop records</a>`:''}</div>`).join('')}</div><div class="card"><h3>Confirmed crop-production areas</h3><div class="tablewrap"><table><thead><tr><th>Area</th><th>Classification</th></tr></thead><tbody>${production.map(([name,type])=>`<tr><td>${name}</td><td>${type}</td></tr>`).join('')}</tbody></table></div><p class="meta">S8 and S9 are Reserve / Habitat. Existing supplied bed measurements remain in the bed register; they do not establish the total property area.</p><a class="btn" href="#beds">View bed register</a></div></section>`;
html = html.replace('  <section id="beds"', areas.replace('the count in each coop is TBC.', '<span class="birdSplit">the count in each coop is TBC.</span>')+'\n  <section id="beds"');
section('coop', `<div class="section-title"><div><h2>Chicken coops</h2><p class="sub">90 chickens across the farm · individual coop counts TBC until entered</p></div><a class="btn" href="#areas">Farm Areas</a></div>
<div class="card"><h3>Bird counts</h3><form id="birdForm"><div class="grid2"><label>Chicken Coop A<input id="birdsA" type="number" min="0" max="90" step="1" placeholder="TBC"></label><label>Chicken Coop B<input id="birdsB" type="number" min="0" max="90" step="1" placeholder="TBC"></label></div><p class="meta">Enter observed counts only. The other coop is never filled automatically. If both counts are entered, they must total 90.</p><button class="btn" type="submit">Save observed counts</button></form></div>
<div class="card"><div class="grid2"><label>Coop<select id="activeCoop"><option>Chicken Coop A</option><option>Chicken Coop B</option></select></label><label>Record date<input id="recordDate" type="date" required></label></div><p class="meta">One daily record per coop and date. Selecting another coop or date loads its own saved values. Blank means Not recorded yet; enter 0 only when observed.</p><p id="recordStatus" role="status"></p></div>
<form id="dailyRecordForm"><div class="card"><h3>Egg collection & stock</h3><div id="eggFields" class="record-grid"></div><p class="meta">When both collection rounds are recorded, eggs collected is their sum. Saleable + broken / dirty must match the collection when all three are entered. Remaining stock is an observed count; it is not inferred from missing opening stock.</p></div><div class="card"><h3>Feed, water & flock health</h3><div id="healthFields" class="record-grid"></div></div><div class="card"><h3>Responsibility & notes</h3><div id="noteFields" class="grid2"></div><p><button class="btn primary" type="submit">Save daily coop record</button></p></div></form>
<div class="card"><h3>Cleaning schedule</h3><p class="meta">Daily mini cleaning · weekly normal cleaning · monthly deep cleaning. Due dates start from actual recorded cleaning or an entered next due date.</p><div id="cleanCards" class="clean-grid"></div></div>
<div class="card"><h3>Record cleaning</h3><form id="cleanForm"><div class="record-grid"><label>Cleaning type<select id="cleanType"><option value="mini">Daily mini cleaning</option><option value="normal">Weekly normal cleaning</option><option value="deep">Monthly deep cleaning</option></select></label><label>Cleaning date<input id="cleanDate" type="date" required></label><label>Worker responsible<input id="cleanWorker" placeholder="Not recorded yet"></label><label>Completion<select id="cleanCompletion" required><option value="">Choose completion</option><option>Completed</option><option>Partial</option><option>Not completed</option></select></label><label>Next cleaning due<input id="cleanNext" type="date"></label><label>Cleaning notes<textarea id="cleanNotes" placeholder="Not recorded yet"></textarea></label></div><p class="meta">For completed cleaning, leaving next due blank schedules one day, one week or one calendar month after the cleaning date.</p><button class="btn primary" type="submit">Save cleaning record</button></form></div>
<div class="card"><h3>Cleaning history · <span id="historyCoop"></span></h3><div id="cleanHistory"></div></div><div class="card"><h3>Daily history · <span id="dailyHistoryCoop"></span></h3><div id="dailyHistory"></div></div>`);
section('eggs', `<div class="section-title"><div><h2>Farm egg dashboard</h2><p class="sub">Totals calculated from separate Chicken Coop A and Chicken Coop B records</p></div><a class="btn primary" href="#coop">Enter coop records</a></div><div class="card"><label>Summary date<input id="summaryDate" type="date" required></label><p class="meta">A farm total is shown only when both coops have recorded that field. Partial subtotals identify missing records.</p><div id="eggSummary" class="record-grid"></div></div><div class="card"><h3>Records by coop</h3><div id="eggHistory"></div></div>`);
html=html.replace('individual coop counts TBC until entered','<span class="birdSplit">individual coop counts TBC until entered</span>');
html=html.replace('value="08:00"','').replace('<th>Progress</th>','').replace('<input id="cropDate" type="date" required>','<input id="cropDate" type="date" aria-label="Planting date (optional)">');
html=html.replace('<div class="date" id="todayLabel">Today</div>', '<div class="date" id="todayLabel">Today</div>').replace('<nav class="tabs">', '<div id="storageNotice" class="notice" hidden role="alert"></div><nav class="tabs">');
html=html.replace('</style>', `
.record-grid{display:grid;grid-template-columns:repeat(3,minmax(0,1fr));gap:16px}label{display:block;font-size:14px}label input,label select,label textarea{margin-top:7px}textarea{width:100%;min-height:88px;border:1px solid var(--line);border-radius:11px;padding:10px;font:inherit;resize:vertical}.notice{background:var(--warn);border-radius:12px;padding:14px;margin-bottom:14px}.facility h3{margin:0 0 12px}.metric strong{font-size:clamp(18px,3vw,30px)}.status{white-space:normal}details{padding:12px 0;border-bottom:1px solid var(--line)}summary{cursor:pointer;line-height:1.7}dl{margin:0}dt{color:var(--muted);font-size:12px;margin-top:12px}dd{margin:4px 0;white-space:pre-wrap;overflow-wrap:anywhere}.tabs a:focus-visible,.btn:focus-visible{outline:3px solid #7aab83;outline-offset:2px}.btn{cursor:pointer;text-decoration:none;display:inline-block}.record-grid>*{min-width:0}h2{margin:0}.section-title{flex-wrap:wrap}@media(max-width:800px){.tabs{display:flex}.record-grid{grid-template-columns:1fr 1fr}}@media(max-width:480px){.record-grid{grid-template-columns:1fr}.grid2{grid-template-columns:1fr}.row{flex-wrap:wrap}}
</style>`);
// Keep supplied reference data; operational defaults are deliberately empty.
const oldScript = html.match(/<script>([\s\S]*?)<\/script>/)[1];
const workerText=oldScript.match(/workers:(\[[\s\S]*?\]),\s*tasks:/)[1];
const inventoryText=oldScript.match(/inventory:(\[[\s\S]*?\]),\s*plans:/)[1];
const script = fs.readFileSync('farm-app.js','utf8').replace('/* WORKERS */[]', workerText).replace('/* INVENTORY */[]',inventoryText);
html=html.replace(/<script>[\s\S]*?<\/script>/,()=>'<script>\n'+script+'\n</script>');
fs.writeFileSync('Green peas Farm Os.html',html);
console.log('Built Green peas Farm Os.html');
