const {chromium}=require('C:/Users/Roger/.cache/codex-runtimes/codex-primary-runtime/dependencies/node/node_modules/playwright');
const assert=require('node:assert/strict');
const fs=require('fs');
const path=require('path');
const {pathToFileURL}=require('url');
(async()=>{
 const browser=await chromium.launch({headless:true});
 const context=await browser.newContext({viewport:{width:1365,height:1000}});
 const page=await context.newPage();
 const errors=[];page.on('pageerror',e=>errors.push(e.message));
 const url=pathToFileURL(path.resolve('Green peas Farm Os.html')).href;
 await page.goto(url+'#areas');
 assert.equal(await page.locator('.facility').count(),15);
 assert.equal(await page.getByText('Pig House',{exact:true}).count(),0);
 assert.equal(await page.locator('#areas tbody tr').count(),19);
 assert.equal(await page.locator('#areas tbody tr').filter({hasText:'Reserve / Habitat'}).count(),2);
 assert.equal(await page.locator('#kpiEggs').textContent(),'Not recorded yet');
 assert.equal(await page.locator('#kpiClean').textContent(),'TBC');
 await page.screenshot({path:'areas-desktop.png',fullPage:true});
 await page.goto(url+'#coop');
 const day=await page.locator('#recordDate').inputValue();
 assert.equal(await page.locator('#birdsA').inputValue(),'');
 assert.equal(await page.locator('#birdsB').inputValue(),'');
 await page.locator('#rec_morning').fill('12');
 await page.locator('#rec_worker').fill('Recorded worker');
 await page.locator('#rec_notes').fill('<img src=x onerror=alert(1)>');
 await page.locator('#dailyRecordForm button[type=submit]').click();
 let state=await page.evaluate(()=>JSON.parse(localStorage.getItem('green_peas_confirmed_v4')));
 assert.equal(state.records[day]['Chicken Coop A'].morning,12);
 assert.equal(state.records[day]['Chicken Coop A'].evening,null);
 assert.equal(state.records[day]['Chicken Coop A'].total,null);
 assert.equal(state.records[day]['Chicken Coop A'].mortality,null);
 assert.equal(state.records[day]['Chicken Coop A'].water,null);
 assert.equal(await page.locator('#dailyHistory img').count(),0);
 await page.locator('#activeCoop').selectOption('Chicken Coop B');
 assert.equal(await page.locator('#rec_morning').inputValue(),'');
 assert.equal(await page.locator('#rec_worker').inputValue(),'');
 await page.locator('#rec_morning').fill('8');await page.locator('#rec_evening').fill('2');await page.locator('#rec_mortality').fill('0');
 await page.locator('#dailyRecordForm button[type=submit]').click();
 assert.match(await page.locator('#kpiEggs').textContent(),/10 recorded · partial/);
 await page.locator('#activeCoop').selectOption('Chicken Coop A');
 assert.equal(await page.locator('#rec_morning').inputValue(),'12');
 await page.locator('#rec_evening').fill('3');await page.locator('#rec_broken').fill('1');await page.locator('#rec_saleable').fill('14');
 await page.locator('#dailyRecordForm button[type=submit]').click();
 assert.equal(await page.locator('#kpiEggs').textContent(),'25');
 await page.locator('#rec_total').fill('99');
 await page.locator('#dailyRecordForm button[type=submit]').click();
 assert.match(await page.locator('#toast').textContent(),/must equal morning/);
 await page.reload();
 assert.equal(await page.locator('#rec_total').inputValue(),'15');
 await page.locator('#birdsA').fill('40');await page.locator('#birdForm button').click();
 assert.equal(await page.locator('#birdsB').inputValue(),'');
 await page.locator('#birdsB').fill('40');await page.locator('#birdForm button').click();
 assert.match(await page.locator('#toast').textContent(),/total 90/);
 state=await page.evaluate(()=>JSON.parse(localStorage.getItem('green_peas_confirmed_v4')));assert.equal(state.birds['Chicken Coop B'],null);
 await page.locator('#birdsB').fill('50');await page.locator('#birdForm button').click();
 await page.locator('#cleanType').selectOption('deep');await page.locator('#cleanDate').fill('2024-01-31');await page.locator('#cleanWorker').fill('Cleaning worker');await page.locator('#cleanCompletion').selectOption('Completed');
 await page.locator('#cleanForm button').click();
 state=await page.evaluate(()=>JSON.parse(localStorage.getItem('green_peas_confirmed_v4')));
 assert.equal(state.cleaning[0].next,'2024-02-29');assert.equal(state.cleaning[0].coop,'Chicken Coop A');
 await page.locator('#activeCoop').selectOption('Chicken Coop B');
 assert.equal(await page.locator('#cleanHistory').textContent(),'Not recorded yet');
 assert.equal(await page.locator('#cleanWorker').inputValue(),'');
 await page.locator('#cleanType').selectOption('normal');await page.locator('#cleanCompletion').selectOption('Partial');await page.locator('#cleanForm button').click();
 state=await page.evaluate(()=>JSON.parse(localStorage.getItem('green_peas_confirmed_v4')));assert.equal(state.cleaning[1].next,null);
 await page.reload();await page.locator('#activeCoop').selectOption('Chicken Coop B');
 assert.equal(await page.locator('#rec_total').inputValue(),'10');assert.equal(await page.locator('#rec_mortality').inputValue(),'0');
 assert.match(await page.locator('#cleanHistory').textContent(),/Partial/);
 // A second date must not overwrite today's records.
 await page.locator('#recordDate').fill('2024-01-30');await page.locator('#recordDate').dispatchEvent('change');
 assert.equal(await page.locator('#rec_morning').inputValue(),'');
 await page.locator('#rec_total').fill('0');await page.locator('#dailyRecordForm button[type=submit]').click();
 state=await page.evaluate(()=>JSON.parse(localStorage.getItem('green_peas_confirmed_v4')));
 assert.equal(state.records['2024-01-30']['Chicken Coop B'].total,0);assert.equal(state.records[day]['Chicken Coop B'].total,10);
 // Re-saving replaces a daily record instead of duplicating counts.
 await page.locator('#dailyRecordForm button[type=submit]').click();
 assert.equal(await page.locator('#kpiEggs').textContent(),'25');
 await page.setViewportSize({width:390,height:844});
 for(const hash of ['areas','coop','eggs','home','farm','beds','tasks','crops','workers','inventory','planting','guide']){
   await page.goto(url+'#'+hash);
   assert.equal(await page.locator('#'+hash).isVisible(),true);
   const overflow=await page.evaluate(()=>document.documentElement.scrollWidth>innerWidth);
   assert.equal(overflow,false,'Mobile overflow on '+hash);
 }
 // Capture clean initial-state UI; fixture data remains in this isolated browser only.
 await page.evaluate(()=>localStorage.clear());await page.goto(url+'#coop');await page.reload();
 await page.screenshot({path:'coop-mobile.png',fullPage:true});
 await page.setViewportSize({width:1365,height:1000});await page.screenshot({path:'coop-desktop.png',fullPage:true});
 // Prior-version storage must be retained without importing fabricated defaults.
 await page.evaluate(()=>localStorage.setItem('green_peas_farm_os_complete_v3',JSON.stringify({eggs:[{count:60}],coopCleaning:{}})));
 await page.reload();assert.equal(await page.locator('#storageNotice').isVisible(),true);assert.equal(await page.locator('#kpiEggs').textContent(),'Not recorded yet');
 assert.ok(await page.evaluate(()=>localStorage.getItem('green_peas_farm_os_complete_v3')));
 assert.deepEqual(errors,[]);
 await browser.close();
 console.log('PASS: confirmed areas; coop isolation; blank versus zero; totals; validation; persistence; cleaning history and calendar recurrence; older data preservation; safe text rendering; all 12 views at mobile width.');
})().catch(e=>{console.error(e);process.exit(1);});
