-- Integration fixtures exist only inside this transaction and are always rolled back.
begin;
create temporary table fixture(k text primary key,id uuid);grant select on fixture to authenticated;
insert into auth.users(id,email) values('11111111-1111-4111-8111-111111111111','farm-test-owner@example.invalid'),('22222222-2222-4222-8222-222222222222','farm-test-worker@example.invalid');
with r as(insert into public.farms(slug,name,total_chickens) values('__rollback_test','Isolated transaction fixture',90) returning id) insert into fixture select 'farm',id from r;
insert into public.farm_members(farm_id,email,user_id,role) select id,'farm-test-owner@example.invalid','11111111-1111-4111-8111-111111111111','owner' from fixture where k='farm';
with r as(insert into public.areas(farm_id,name,kind) select id,'Fixture area','production' from fixture where k='farm' returning id) insert into fixture select 'area',id from r;
with r as(insert into public.beds(farm_id,area_id,code,purpose) select f.id,a.id,'Fixture bed','Production' from fixture f,fixture a where f.k='farm' and a.k='area' returning id) insert into fixture select 'bed',id from r;
with r as(insert into public.workers(farm_id,name) select id,'Fixture worker A' from fixture where k='farm' returning id) insert into fixture select 'worker1',id from r;
with r as(insert into public.workers(farm_id,name) select id,'Fixture worker B' from fixture where k='farm' returning id) insert into fixture select 'worker2',id from r;
insert into public.farm_members(farm_id,email,user_id,role,worker_id) select f.id,'farm-test-worker@example.invalid','22222222-2222-4222-8222-222222222222','worker',w.id from fixture f,fixture w where f.k='farm' and w.k='worker1';
with r as(insert into public.coops(farm_id,name,bird_count) select id,'Chicken Coop A',40 from fixture where k='farm' returning id) insert into fixture select 'coopA',id from r;
with r as(insert into public.coops(farm_id,name,bird_count) select id,'Chicken Coop B',50 from fixture where k='farm' returning id) insert into fixture select 'coopB',id from r;
with r as(insert into public.crops(farm_id,name) select id,'Fixture crop' from fixture where k='farm' returning id) insert into fixture select 'crop',id from r;
select set_config('request.jwt.claims','{"sub":"11111111-1111-4111-8111-111111111111","email":"farm-test-owner@example.invalid","role":"authenticated"}',true);
set local role authenticated;
do $$declare fid uuid:=(select id from fixture where k='farm');pid uuid;tid uuid;inv uuid;product uuid;menu uuid;conv uuid;proposal uuid;requestid uuid:=gen_random_uuid();a uuid:=(select id from fixture where k='coopA');b uuid:=(select id from fixture where k='coopB');rejected boolean;v numeric;begin
 if (select count(*) from public.farms)<>1 then raise exception 'RLS isolation failed';end if;
 insert into public.plantings(farm_id,crop_id,bed_id,stage) values(fid,(select id from fixture where k='crop'),(select id from fixture where k='bed'),'Ready to harvest') returning id into pid;
 perform public.change_crop_stage(pid,'advance');if (select stage from public.plantings where id=pid)<>'Finished' then raise exception 'Advance failed';end if;
 rejected:=false;begin perform public.change_crop_stage(pid,'advance');exception when others then rejected:=true;end;if not rejected then raise exception 'Finished advanced';end if;
 perform public.change_crop_stage(pid,'previous','Fixture reversal');if (select count(*) from public.crop_stage_history where planting_id=pid)<>2 then raise exception 'Stage audit failed';end if;
 tid:=public.save_scheduled_task(fid,null,jsonb_build_object('title','Fixture shared task','scheduled_date',current_date,'recurrence','One-time','assignee_ids',jsonb_build_array((select id from fixture where k='worker1'),(select id from fixture where k='worker2'))),'Open');
 if (select count(*) from public.task_assignees where task_id=tid)<>2 then raise exception 'Multi-assignment failed';end if;
 perform public.set_task_status(tid,current_date,'Completed');if (select completed_by from public.tasks where id=tid)<>auth.uid() then raise exception 'Completion actor missing';end if;
 perform public.adjust_chickens(a,'Add',5,'Fixture addition');perform public.adjust_chickens(a,'Remove',5,'Fixture removal');perform public.adjust_chickens(a,'Transfer',5,'Fixture transfer',null,b);
 if (select bird_count from public.coops where id=a)<>35 or (select bird_count from public.coops where id=b)<>55 or (select total_chickens from public.farms where id=fid)<>90 then raise exception 'Flock transfer failed';end if;
 rejected:=false;begin perform public.adjust_chickens(a,'Remove',1000,'Fixture rejected');exception when others then rejected:=true;end;if not rejected then raise exception 'Negative flock accepted';end if;
 insert into public.inventory(farm_id,item,category,qty,unit,coop_id) values(fid,'Fixture eggs','Eggs',100,'egg',a) returning id into inv;
 product:=public.save_marketplace_product(fid,null,jsonb_build_object('name','Fixture product','source','Eggs','inventory_id',inv,'unit','egg','stock_per_unit',1,'status','Available','price',2,'currency','Fixture'));
 perform public.record_marketplace_sale(product,3,current_date,requestid);perform public.record_marketplace_sale(product,3,current_date,requestid);
 if (select qty from public.inventory where id=inv)<>97 or (select count(*) from public.marketplace_transactions where request_id=requestid)<>1 then raise exception 'Idempotent sale failed';end if;
 menu:=public.save_breakfast_item(fid,null,'{"name":"Fixture breakfast","active":true,"quantity_available":0}',jsonb_build_array(jsonb_build_object('inventory_id',inv,'quantity_per_serving',2)));
 perform public.record_breakfast(menu,'Prepared',4,current_date,gen_random_uuid());perform public.record_breakfast(menu,'Served',2,current_date,gen_random_uuid());
 if (select qty from public.inventory where id=inv)<>89 or (select quantity_available from public.breakfast_items where id=menu)<>2 then raise exception 'Breakfast shared stock failed';end if;
 if (select count(*) from public.inventory_transactions where inventory_id=inv and type='Breakfast Usage')<>1 then raise exception 'Ingredient audit failed';end if;
 insert into public.ai_conversations(farm_id) values(fid) returning id into conv;
 insert into public.ai_actions(farm_id,conversation_id,action,summary,arguments) values(fid,conv,'update_marketplace_stock','Fixture cancellation',jsonb_build_object('inventory_id',inv,'quantity',70,'expected_updated_at',(select updated_at from public.inventory where id=inv))) returning id into proposal;
 perform public.decide_ai_action(proposal,false);if (select qty from public.inventory where id=inv)<>89 then raise exception 'Cancel changed stock';end if;
 insert into public.ai_actions(farm_id,conversation_id,action,summary,arguments) values(fid,conv,'update_marketplace_stock','Fixture confirmation',jsonb_build_object('inventory_id',inv,'quantity',70,'expected_updated_at',(select updated_at from public.inventory where id=inv))) returning id into proposal;
 perform public.decide_ai_action(proposal,true);perform public.decide_ai_action(proposal,true);
 if (select qty from public.inventory where id=inv)<>70 or (select count(*) from public.ai_audit_log where action_id=proposal)<>1 then raise exception 'Confirmed action duplicated';end if;
end $$;
select set_config('request.jwt.claims','{"sub":"22222222-2222-4222-8222-222222222222","email":"farm-test-worker@example.invalid","role":"authenticated"}',true);
do $$declare fid uuid:=(select id from fixture where k='farm');tid uuid;conv uuid;proposal uuid;rejected boolean;begin
 select id into tid from public.tasks where title='Fixture shared task';if tid is null then raise exception 'Assigned worker task invisible';end if;
 perform public.set_task_status(tid,current_date,'Open');perform public.set_task_status(tid,current_date,'Completed');
 if (select completed_by from public.tasks where id=tid)<>auth.uid() then raise exception 'Worker completion actor failed';end if;
 if exists(select 1 from public.ai_conversations) then raise exception 'Conversation privacy failed';end if;
 insert into public.ai_conversations(farm_id) values(fid) returning id into conv;
 insert into public.ai_actions(farm_id,conversation_id,action,summary,arguments) values(fid,conv,'adjust_chicken_count','Fixture permission rejection',jsonb_build_object('coop_id',(select id from fixture where k='coopA'),'action','Add','quantity',1,'reason','Fixture')) returning id into proposal;
 rejected:=false;begin perform public.decide_ai_action(proposal,true);exception when others then rejected:=true;end;if not rejected then raise exception 'Worker bypassed AI permissions';end if;
 rejected:=false;begin insert into public.inventory(farm_id,item,category) values(fid,'Unauthorized fixture','Fixture');exception when others then rejected:=true;end;if not rejected then raise exception 'Worker direct write allowed';end if;
end $$;
reset role;
rollback;
select 'All transactional integration checks passed; all fixtures rolled back.' as result;
