-- Run through a database administrator. Every fixture and change is rolled back.
begin;
create temporary table fixture(k text primary key,id uuid);grant select on fixture to anon;
insert into fixture select 'farm',id from public.farms where slug='green-peas';
insert into fixture select 'coopA',id from public.coops where name='Chicken Coop A' and farm_id=(select id from fixture where k='farm');
insert into fixture select 'coopB',id from public.coops where name='Chicken Coop B' and farm_id=(select id from fixture where k='farm');
select set_config('request.jwt.claims','{"role":"anon"}',true);
set local role anon;
do $$declare fid uuid:=(select id from fixture where k='farm');t text;tid uuid;pid uuid;inv uuid;product uuid;menu uuid;conv uuid;proposal uuid;requestid uuid:=gen_random_uuid();a uuid:=(select id from fixture where k='coopA');b uuid:=(select id from fixture where k='coopB');rejected boolean;cropid uuid;bedid uuid;wids jsonb;begin
 if not public.can_access_farm(fid) or not public.can_manage_farm(fid) or auth.uid() is not null then raise exception 'Temporary anonymous access failed';end if;
 foreach t in array array['areas','beds','workers','coops','crops','plantings','planting_plans','tasks','task_occurrences','coop_daily_records','coop_cleaning','inventory','harvest_records','farm_records','task_assignees','crop_stage_history','chicken_count_history','farm_seasons','marketplace_products','marketplace_transactions','breakfast_items','breakfast_ingredients','breakfast_records','inventory_transactions','ai_conversations','ai_messages','ai_actions','ai_audit_log'] loop execute format('select count(*) from public.%I',t);end loop;
 rejected:=false;begin rejected:=not exists(select 1 from public.farm_members);exception when insufficient_privilege then rejected:=true;end;if not rejected then raise exception 'Private memberships exposed';end if;
 select jsonb_agg(id) into wids from(select id from public.workers where farm_id=fid limit 2) w;
 tid:=public.save_scheduled_task(fid,null,jsonb_build_object('title','Transaction-only task fixture','scheduled_date',current_date,'recurrence','Daily','assignee_ids',wids),'Open');
 perform public.set_task_status(tid,current_date,'Completed');
 if not exists(select 1 from public.task_occurrences where task_id=tid and status='Completed' and completed_at is not null and completed_by is null) then raise exception 'Shared task completion or anonymous audit failed';end if;
 if (select count(*) from public.task_assignees where task_id=tid)<>jsonb_array_length(wids) then raise exception 'Assignment relationships failed';end if;
 insert into public.crops(farm_id,name) values(fid,'Transaction-only crop fixture') returning id into cropid;
 select id into bedid from public.beds where farm_id=fid and purpose='Production' limit 1;
 insert into public.plantings(farm_id,crop_id,bed_id,stage) values(fid,cropid,bedid,'Ready to harvest') returning id into pid;
 perform public.change_crop_stage(pid,'advance');perform public.change_crop_stage(pid,'previous','Transaction-only reversal');
 if (select count(*) from public.crop_stage_history where planting_id=pid)<>2 then raise exception 'Crop lifecycle audit failed';end if;
 insert into public.planting_plans(farm_id,crop_id,bed_id,planned_on) values(fid,cropid,bedid,current_date);
 perform public.set_coop_counts(fid,2,3);perform public.adjust_chickens(a,'Add',1,'Transaction-only addition');perform public.adjust_chickens(a,'Remove',1,'Transaction-only removal');perform public.adjust_chickens(a,'Transfer',1,'Transaction-only transfer',null,b);
 if (select bird_count from public.coops where id=a)<>1 or (select bird_count from public.coops where id=b)<>4 or (select total_chickens from public.farms where id=fid)<>5 then raise exception 'Flock transfer failed';end if;
 insert into public.coop_daily_records(farm_id,coop_id,record_date,morning,evening,total,feed,water) values(fid,a,'1900-01-01',1,1,2,1,'Checked') on conflict(coop_id,record_date) do update set morning=1,evening=1,total=2,feed=1,water='Checked';
 insert into public.coop_cleaning(farm_id,coop_id,type,cleaning_date,completion) values(fid,a,'mini',current_date,'Completed');
 insert into public.inventory(farm_id,item,category,qty,unit) values(fid,'Transaction-only stock fixture','Fixture',100,'egg') returning id into inv;
 product:=public.save_marketplace_product(fid,null,jsonb_build_object('name','Transaction-only product fixture','source','Other farm products','inventory_id',inv,'unit','egg','stock_per_unit',1,'status','Available'));
 perform public.record_marketplace_sale(product,3,current_date,requestid);perform public.record_marketplace_sale(product,3,current_date,requestid);
 if (select qty from public.inventory where id=inv)<>97 then raise exception 'Sale or idempotency failed';end if;
 menu:=public.save_breakfast_item(fid,null,'{"name":"Transaction-only breakfast fixture","active":true,"quantity_available":0}',jsonb_build_array(jsonb_build_object('inventory_id',inv,'quantity_per_serving',2)));
 perform public.record_breakfast(menu,'Prepared',4,current_date,gen_random_uuid());perform public.record_breakfast(menu,'Served',2,current_date,gen_random_uuid());
 if (select qty from public.inventory where id=inv)<>89 then raise exception 'Breakfast inventory failed';end if;
 insert into public.ai_conversations(farm_id,title) values(fid,'Transaction-only conversation fixture') returning id into conv;
 insert into public.ai_messages(farm_id,conversation_id,role,content) values(fid,conv,'user','Transaction-only message fixture');
 insert into public.ai_actions(farm_id,conversation_id,action,summary,arguments) values(fid,conv,'update_marketplace_stock','Transaction-only cancellation',jsonb_build_object('inventory_id',inv,'quantity',70,'expected_updated_at',(select updated_at from public.inventory where id=inv))) returning id into proposal;
 perform public.decide_ai_action(proposal,false);if (select qty from public.inventory where id=inv)<>89 then raise exception 'Cancellation mutated stock';end if;
 insert into public.ai_actions(farm_id,conversation_id,action,summary,arguments) values(fid,conv,'update_marketplace_stock','Transaction-only confirmation',jsonb_build_object('inventory_id',inv,'quantity',70,'expected_updated_at',(select updated_at from public.inventory where id=inv))) returning id into proposal;
 perform public.decide_ai_action(proposal,true);perform public.decide_ai_action(proposal,true);
 if (select qty from public.inventory where id=inv)<>70 or (select count(*) from public.ai_audit_log where action_id=proposal)<>1 then raise exception 'Confirmed action atomicity failed';end if;
end $$;
reset role;
update farm_internal.temporary_access_window set expires_at=now()-interval '1 second';
set local role anon;
do $$declare fid uuid:=(select id from fixture where k='farm');rejected boolean;begin
 if public.can_access_farm(fid) or public.can_manage_farm(fid) or exists(select 1 from public.farms) or exists(select 1 from public.inventory) then raise exception 'Temporary access did not expire';end if;
 rejected:=false;begin perform public.set_coop_counts(fid,2,3);exception when others then rejected:=true;end;if not rejected then raise exception 'Write RPC remained accessible after expiry';end if;
 rejected:=false;begin insert into public.tasks(farm_id,title) values(fid,'Must be rejected');exception when insufficient_privilege then rejected:=true;end;if not rejected then raise exception 'Direct writes remained accessible after expiry';end if;
end $$;
reset role;
rollback;
select 'PASS: anonymous workflows, shared task status, audited stock, confirmed AI actions, privacy and automatic expiry; all fixtures rolled back.' as result;
